name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: vuepress-deploy
        uses: sin2cr/manual@main
        env:
          ACCESS_TOKEN: ${{ secrets.DEPLOY}}
          TARGET_REPO: sin2cr/manual
          TARGET_BRANCH: deploy_pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist