# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on: 
# [push]
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@main
        
        - name: Install and Build
          run: |
            yarn install
            yarn run build

        - name: vuepress-deploy
          uses: sin2cr/manual@main
          env:
            ACCESS_TOKEN: ${{ secrets.DEPLOY}}
            TARGET_REPO: sin2cr/manual
            TARGET_BRANCH: deploy_pages
            BUILD_SCRIPT: yarn && yarn build
            BUILD_DIR: docs/.vuepress/dist